In [1]:
import gym
import numpy as np
import tensorflow as tf
import pickle
import os
from os import path

In [2]:
model = tf.keras.models.load_model(
    './cartpole_system_model', custom_objects=None, compile=True, options=None
)

2022-03-10 03:56:01.191060: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [11]:
np_weights = model.get_weights()
print("A Matrix")
print(np_weights[0])
print("B Matrix")
print(np_weights[2])

A Matrix
[[ 0.6364069   0.95900077  0.12296377  0.29094964]
 [ 0.26316372  0.43023634 -0.08147145 -0.32828495]
 [-0.6197034  -0.35744616  1.2098693   0.7076696 ]
 [ 0.18480468 -0.28356367 -0.04188489  0.7647021 ]]
B Matrix
[[ 1.2779693e-04  3.9283797e-01 -4.7948357e-05 -5.7771873e-01]]


In [9]:
model.A.get_weights()

[array([[ 0.6364069 ,  0.95900077,  0.12296377,  0.29094964],
        [ 0.26316372,  0.43023634, -0.08147145, -0.32828495],
        [-0.6197034 , -0.35744616,  1.2098693 ,  0.7076696 ],
        [ 0.18480468, -0.28356367, -0.04188489,  0.7647021 ]],
       dtype=float32),
 array([ 1.6391998e-04, -9.6513622e-02, -6.8874164e-05,  1.4688468e-01],
       dtype=float32)]

In [10]:
model.B.get_weights()

[array([[ 1.2779693e-04,  3.9283797e-01, -4.7948357e-05, -5.7771873e-01]],
       dtype=float32),
 array([ 1.6391998e-04, -9.6513622e-02, -6.8874164e-05,  1.4688468e-01],
       dtype=float32)]

In [ ]:
# the model Dense layers have biases on them. These should be removed to get the true A and B matrices