In [1]:
import gym
import numpy as np
import tensorflow as tf
import pickle
import os
from os import path

In [2]:
model = tf.keras.models.load_model(
    './cartpole_system_model', custom_objects=None, compile=True, options=None
)

2022-03-10 08:51:18.305700: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
np_weights = model.get_weights()
print(model.A.get_weights())
print(model.B.get_weights())

[array([[ 0.9248389 ,  0.50807655, -0.13568638,  0.23905176],
       [ 0.06506144,  0.50349087,  0.08545925, -0.75586605],
       [-0.13493538,  0.82650167,  0.7027278 ,  1.3792988 ],
       [ 0.03512419, -0.3653296 ,  0.09017479,  0.44217753]],
      dtype=float32)]
[array([[-9.2811701e-05,  1.9885701e-01,  1.7286059e-04, -2.8716338e-01]],
      dtype=float32)]


In [8]:
print("A Matrix")
print(np_weights[0])
print("B Matrix")
print(np_weights[1].T)

A Matrix
[[ 0.9248389   0.50807655 -0.13568638  0.23905176]
 [ 0.06506144  0.50349087  0.08545925 -0.75586605]
 [-0.13493538  0.82650167  0.7027278   1.3792988 ]
 [ 0.03512419 -0.3653296   0.09017479  0.44217753]]
B Matrix
[[-9.2811701e-05]
 [ 1.9885701e-01]
 [ 1.7286059e-04]
 [-2.8716338e-01]]
