In [1]:
import gym
import numpy as np
import tensorflow as tf
import pickle
import os
from os import path

In [2]:
model = tf.keras.models.load_model(
    './cartpole_system_model', custom_objects=None, compile=True, options=None
)

2022-03-08 13:55:42.614163: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
np_weights = model.get_weights()
print("A Matrix")
print(np_weights[0])
print("B Matrix")
print(np_weights[1])

A Matrix
[[ 0.6364069   0.95900077  0.12296377  0.29094964]
 [ 0.26316372  0.43023634 -0.08147145 -0.32828495]
 [-0.6197034  -0.35744616  1.2098693   0.7076696 ]
 [ 0.18480468 -0.28356367 -0.04188489  0.7647021 ]]
B Matrix
[ 1.6391998e-04 -9.6513622e-02 -6.8874164e-05  1.4688468e-01]
