In [32]:
import gym
import numpy as np
import tensorflow as tf
import pickle
import os
from os import path

In [33]:
model = tf.keras.models.load_model(
    './cartpole_system_model', custom_objects=None, compile=True, options=None
)

In [34]:
np_weights = model.get_weights()
print(model.A.get_weights())
print(model.B.get_weights())

[array([[ 1.00000298e+00,  1.03474304e-01, -6.81955644e-05,
        -1.53411880e-01],
       [ 2.00001802e-02,  9.95905221e-01, -1.23909122e-05,
         6.26267958e-03],
       [-5.69764438e-07, -5.87693080e-02,  1.00003278e+00,
         3.81267816e-01],
       [ 3.71733137e-07, -1.13821297e-03,  2.00367365e-02,
         1.00111854e+00]], dtype=float32)]
[array([[-2.2487126e-07,  1.9629727e-01,  2.1716911e-05, -2.9252878e-01]],
      dtype=float32)]


In [37]:
print("A Matrix")
print(np_weights[0])
print("B Matrix")
print(np_weights[1].T)

A Matrix
[[ 1.00000298e+00  1.03474304e-01 -6.81955644e-05 -1.53411880e-01]
 [ 2.00001802e-02  9.95905221e-01 -1.23909122e-05  6.26267958e-03]
 [-5.69764438e-07 -5.87693080e-02  1.00003278e+00  3.81267816e-01]
 [ 3.71733137e-07 -1.13821297e-03  2.00367365e-02  1.00111854e+00]]
B Matrix
[[-2.2487126e-07]
 [ 1.9629727e-01]
 [ 2.1716911e-05]
 [-2.9252878e-01]]
